services:
  postgres:
    image: postgres:16-alpine
    container_name: general-ledger-postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-general_ledger}
      POSTGRES_USER: ${POSTGRES_USER:-general_ledger}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-general_ledger}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
