spring:
  application:
    name: ledger
  
  # Liquibase Configuration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: none  # Let Liquibase handle schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Database Configuration (matches docker-compose.yml defaults)
  datasource:
    url: jdbc:postgresql://localhost:5432/general_ledger
    username: general_ledger
    password: general_ledger
    driver-class-name: org.postgresql.Driver
  
  # DevTools Configuration
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**

# Actuator Configuration (base configuration for all profiles)
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    db:
      enabled: true
    defaults:
      enabled: true

# API Configuration
api:
  base-path: /api/v1

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  packages-to-scan: com.cxm360.ai.ledger.controller
