spring:
  config:
    activate:
      on-profile: prod
  
  # Production logging
  logging:
    level:
      com.cxm360.ai.ledger: INFO
      org.springframework.web: WARN
  
  # Production JPA settings
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Production actuator configuration (minimal for security)
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      show-components: never
