spring:
  application:
    name: ledger
  
  # Liquibase Configuration
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: none  # Let Liquibase handle schema
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Database Configuration (matches docker-compose.yml defaults)
  datasource:
    url: jdbc:postgresql://localhost:5432/general_ledger
    username: general_ledger
    password: general_ledger
    driver-class-name: org.postgresql.Driver
  
  # DevTools Configuration
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**
